# add your desired knowledge graph components here

dataset:
  represented_as: node
  input_label: dataset
  properties:
    conformsTo: str

data catalog:
  is_a: dataCatalog
  represented_as: node
  input_label: dataCatalog

dataset to data catalog edge:
  is_a: [includedInDataCatalog, thing]
  represented_as: edge
  input_label: dataset_dataCatalog_edge
