# add your desired knowledge graph components here

dataset:
  #   is_a: dataset
  represented_as: node
  input_label: dataset
#   properties:
#     name: str[]
#     weight: float

creative work:
  is_a: creativeWork
  represented_as: node
  input_label: creativeWork

# conforms to:
#   is_a: "http://purl.org/dc/terms/conformsTo"
#   represented_as: edge
#   input_label: dataset_creativeWork_association

data catalog:
  is_a: dataCatalog
  represented_as: node
  input_label: dataCatalog

dataset to data catalog edge:
  is_a: [includedInDataCatalog, thing]
  #   is_a: includedInDataCatalog
  represented_as: edge
  input_label: dataset_dataCatalog_edge
